[project]
name = "django-starter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.7",
    "django-unfold>=0.69.0",
    "django-vite>=3.1.0",
    "dotenv>=0.9.9",
    "psycopg2-binary>=2.9.11",
    "whitenoise>=6.11.0",
]
